package com.aman.acceptance.loyalty.enums;
public enum ErrorCode {
    LOYALTY_ACCOUNT_NOT_FOUND,
    LOYALTY_INSUFFICIENT_AVAILABLE_POINTS,
    LOYALTY_OTP_INVALID,
    LOYALTY_OTP_EXPIRED,
    LOYALTY_OTP_ATTEMPTS_EXCEEDED,
    LOYALTY_REDEMPTION_STATE_CONFLICT,
    INVALID_PAYLOAD,
    INTERNAL_SERVER_ERROR,
    DUPLICATE_PURCHASE_TRANSACTION_ID
}

