package com.aman.acceptance.loyalty.enums;

public enum ErrorCode {
    // Refund Service Flow 5
    LOYALTY_ACCOUNT_ALREADY_FROZEN,
    LOYALTY_ACCOUNT_FROZEN,
    LOYALTY_ACCOUNT_NOT_FOUND,
    LOYALTY_ACCOUNT_NOT_FROZEN,
    LOYALTY_PROGRAM_NOT_FOUND,
    LOYALTY_PROGRAM_INACTIVE,
    REFUND_AMOUNT_EXCEEDED,
    INVALID_REFUND_STATE,
    INVALID_FULL_REFUND,
    INVALID_PARTIAL_REFUND,
    POINTS_LOT_NOT_FOUND,
    ORIGINAL_TRANSACTION_NOT_FOUND,
    UNSUPPORTED_CURRENCY,
    POINTS_NOT_LOCKED,
    REFUND_WINDOW_EXPIRED,
    INVALID_ORIGINAL_AMOUNT,
    INVALID_ORIGINAL_POINTS,
    REFUND_IDEMPOTENCY_CONFLICT,
    NEGATIVE_LOCKED_BALANCE,
    REFUND_POINTS_EXCEEDED,

    // ProgramRules Flow 7
    LOYALTY_PROGRAM_NOT_FOUND,
    LOYALTY_RULE_NOT_FOUND,
    INVALID_RULE_EFFECTIVE_DATE,
    RULE_EFFECTIVE_PERIOD_CONFLICT,
    INVALID_LOCK_DAYS,
    INVALID_EXPIRY_DAYS,
    INVALID_EARNING_RULE,
    INVALID_ROUNDING_MODE,
    INVALID_REDEMPTION_RULE


}