# Server Configuration
server.port=8080
server.servlet.context-path=/api/v1/loyalty

# Application Name
spring.application.name=loyalty.service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/aman_loyalty
spring.datasource.username=judejohn
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson Configuration
spring.jackson.default-property-inclusion=non_null

# Custom Loyalty Rules & Config
loyalty.rules.default-lock-days=30
loyalty.rules.default-expiry-days=360
loyalty.rules.default-earning-rate=1.00
loyalty.rules.default-redemption-rate=0.005
loyalty.conversion.conversionOfMoney=1
loyalty.conversion.rateOfPoint=0.005

loyalty.otp.length=6
loyalty.otp.ttl-seconds=120
loyalty.otp.max-attempts=3

# Logging Configuration
logging.level.com.aman.loyalty=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# SpringDoc & Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.show-actuator=false

# Encryption
loyalty.security.secret-key=1234567890123456
